import Head from "next/head";
import React from "react";
import { Navbar } from "../components";

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Sneakers Ecommerce website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>{children}</main>
    </div>
  );
};

export default Layout;
