import Head from "next/head";
import { SingleProduct, HeaderBanner } from "../components";
import { clientSanity } from "../libraries/client";
import styles from "../styles/Home.module.css";

export default function Home({ products, bannerData }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="header-banner my-16">
        <HeaderBanner headerBanner={bannerData && bannerData[0]} />
      </section>
      <section className="produts my-32">
        <div className="mx-0 my-auto">
          <h2 className="text-orange-700 capitalize font-bold tracking-widest text-2xl text-center my-4">Best Seller Sneakers
          </h2>
        </div>
        <div
          onClick={(event) => console.log(event.target)}
          className="grid xl:grid-cols-4 lg:grid-cols-3 md:grid-cols-2 sm:grid-cols-2 w-full gap-4 my-16">
          {products?.map((product) => (
            <SingleProduct key={product._id} product={product} />
          ))}
        </div>
      </section>
    </div>
  );
}

export const getServerSideProps = async () => {
  const query = '*[_type == "product"]';
  const products = await clientSanity.fetch(query);
  const bannerQuery = '*[_type == "banner"]';
  const bannerData = await clientSanity.fetch(bannerQuery);

  return {
    props: { products, bannerData },
  };
};
